#! /bin/sh

# gtk themes and term colorsheme
cp -r ~/Public/theme\ and\ icons/bsp/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/bsp/settings.ini ~/.config/gtk-3.0/ &
xrdb merge ~/.Xresources &

picom &

# workspaces 

external_monitor=$(xrandr --query | grep 'HDMI-1-0')

if [[ $external_monitor = HDMI-1-0\ connected* ]]; then
    xrandr --output eDP-1 --mode 1920x1080 --primary --rotate normal --output HDMI-1-0 --mode 2560x1440 --rotate normal --right-of eDP-1
	bspc monitor eDP-1 -d 1 2 3 4 5
	bspc monitor HDMI-1-0 -d 1 2 3 4 5
	feh --bg-fill ~/Pictures/wall/benord.png ~/Pictures/wall/raindrops-3_6K.jpg;
else
	xrandr --output eDP-1 --auto
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
	feh --bg-fill ~/Pictures/wall/neon.png
fi

#wallpaper and nvim
del .config/nvim && cp -r ~/Public/nvim_confs/base/nvim ~/.config/ &

bspc config focus_follows_pointer true

bspc config top_padding 20

# polybar 
cp -r ~/Public/poly/bsp/polybar ~/.config/ &
~/.config/polybar/launch.sh &

sxhkd -c ~/.config/sxhkd & 
#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

# borders
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

#gaps 
bspc config gapless_monocle false
bspc config window_gap 15
bspc config split_ratio 0.50
